from dataclasses import dataclass

@dataclass
class Property:
    """
    A class to represent a property investment.

    This class models the essential characteristics of a property investment,
    including its purchase price, work cost, rental income, and other related
    parameters to calculate profitability, cash flow, and total investment.

    Attributes:
        value (float): The purchase price of the property.
        work_cost (float): The cost of work or renovations on the property.
        furniture (float): The cost of fourniture 
        contribution (float): The owner's initial contribution or down payment.
        monthly_rent (float): The monthly rental income generated by the property.
        rental_vacancies (float): The number of months the property is expected to be vacant.
        expenses (float): The annual expenses related to the property (taxes, maintenance, etc.).
    """
    price: float
    work_cost: float
    furniture: float
    contribution: float
    monthly_rent: float
    rental_vacancies: float
    expenses: float

    def get_operation_cost(self) -> float:
        """
        Calculate total cost of acquisition. Including agency and notary fees,
        work, furniture cost and owner's contribution.
        """
        return self.price + self.work_cost + self.furniture


    def get_loan_amount(self) -> float:
        """
        Calculate and return the total property cost including fees and the cost of work.

        This method calculates the total amount invested in the property, which is the sum
        of the property's purchase price, cost fees and the cost of any renovations or work.

        Returns:
            float: The total cost of the property, including the purchase price and work cost.
        """
        return self.get_operation_cost() - self.contribution
    
    
    def get_rental_vacancies_amount(self) -> float:
        """
        Calculate and return the total annual cost of rental vacations.
        """
        return self.rental_vacancies * self.monthly_rent


    def get_turnover_amount(self) -> float:
        """
        Calculate and return total turnover for the year, excluding vacation time.
        """
        return (self.monthly_rent * 12) - self.get_rental_vacancies_amount()
    

    def get_net_income_amount(self) -> float:
        """
        Calculate and return net income, turnover - expenses.
        """
        return self.get_turnover_amount() - self.expenses


    def profitability(self) -> float:
        """
        Calculate the profitability percentage of the property investment.

        This method computes the profitability of the property by taking into account
        the rental income, vacancies, expenses, and the total investment (property value 
        plus work cost minus owner's contribution).

        Returns:
            float: The profitability of the property as a percentage.
        """
        return (self.get_net_income_amount() / self.get_loan_amount()) * 100


    def calculate_cashflow_pretax(self, monthly_payment: float) -> float:
        """
        Calculate the pre-tax cash flow of the property.

        The pre-tax cash flow is the difference between the monthly rental income,
        the monthly loan payment, and the monthly expenses related to the property.
        This calculation does not include taxes but gives an estimate of the gross 
        cash flow generated by the property.

        Args:
            monthly_payment (float): The monthly payment of the property loan.

        Returns:
            float: The pre-tax cash flow of the property.
        """ 
        return self.get_net_income_amount() - (monthly_payment * 12)


@dataclass
class Loan:
    """
    A class to represent a loan.

    This class models a loan with its principal amount, interest rate, duration, 
    and associated insurance costs. It provides methods to calculate monthly 
    payments, total loan cost, loan cost (interest and insurance), and the 
    total monthly payment (including loan and property expenses).

    Attributes:
        amount (float): The principal amount of the loan.
        interest_rate (float): The annual interest rate for the loan as a percentage.
        duration_years (float): The duration of the loan in years.
        loan_insurance_cost (float): The monthly cost of loan insurance.
        pno_insurance_cost (float): The monthly cost of owner’s insurance (PNO).
    """
    amount: float
    interest_rate: float
    duration_years: float
    loan_insurance_cost: float
    pno_insurance_cost: float

    def get_monthly_insurance_costs(self) -> float:
        """
        Calculate yearly insurance costs (sum of loan insurance and PNO insurance).
        """
        return self.loan_insurance_cost + self.pno_insurance_cost

    
    def get_loan_monthly_payment(self) -> float:
        """
        Calculate the monthly payment for the loan, without insurance costs.

        This method calculates the monthly payment using the loan amount, interest rate,
        and duration (in years). It also adds the loan insurance and PNO insurance costs 
        to the monthly payment.

        Formula used: 
            Monthly Payment = Loan Amount * (r * (1 + r)^n) / ((1 + r)^n - 1)
            Where:
                r = monthly interest rate
                n = number of months

        Args:
            None

        Returns:
            float: The total monthly payment, including both the loan monthly repayment.
        """
        # Monthly interest rate
        r = self.interest_rate / 100 / 12
        # Number of monthly payments
        n = self.duration_years * 12
        # Monthly payment without insurance
        monthly_payment = self.amount * (r * (1 + r) ** n) / ((1 + r) ** n - 1)
        # Return the total monthly payment including insurance
        return monthly_payment
    

    def get_loan_insurance_monthly_payment(self) -> float:
        """
        Calculate the monthly payment for the loan, including insurance costs.
        Returns:
            float: The total monthly payment, including both the loan monthly repayment and insurance costs.
        """
        return self.get_loan_monthly_payment() + self.get_monthly_insurance_costs()


    def total_cost(self) -> float:
        """
        Calculate the total cost of the loan over its entire duration, including insurance.

        This method calculates the total amount paid over the life of the loan, which is
        the sum of all monthly payments (principal and insurance) over the loan duration.

        Args:
            None

        Returns:
            float: The total cost of the loan, including interest and insurance over the loan's duration.
        """
        # Calculate the monthly payment
        monthly_payment = self.get_loan_insurance_monthly_payment()
        # Calculate the total cost over the loan duration (number of months)
        n = self.duration_years * 12
        return monthly_payment * n


    def loan_cost(self) -> float:
        """
        Calculate the cost of the loan, which is the total paid amount minus the original loan amount.

        This method calculates how much extra has been paid over the life of the loan,
        including interest and insurance costs. It is the total cost minus the original loan principal.

        Args:
            None

        Returns:
            float: The total cost of the loan minus the original loan amount (i.e., interest and insurance costs).
        """
        return self.total_cost() - self.amount
    

    def calculate_loan_and_expenses(self, monthly_payment: float, expenses: float) -> float:
        """
        Calculate the total monthly payment including both the loan payment and property-related expenses.

        This method computes the total monthly amount that needs to be paid, which includes:
        - The loan monthly payment (calculated by `calculate_monthly_payment()`).
        - The monthly equivalent of annual property expenses (e.g., maintenance, taxes).

        The function assumes that the expenses parameter is provided as an annual value, 
        and it divides this amount by 12 to get the monthly cost.

        Args:
            monthly_payment (float): The monthly loan payment (calculated by `calculate_monthly_payment()`).
            expenses (float): The annual property-related expenses (e.g., taxes, maintenance, insurance).

        Returns:
            float: The total monthly payment, which is the sum of the loan payment and the monthly equivalent of the expenses.
        """
        # Convert annual expenses to monthly and add it to the loan monthly payment
        loan_and_expenses_payment = monthly_payment + (expenses / 12)
        return loan_and_expenses_payment